language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-blog-playground' ]; then cd .. && eval "mv $currentfolder generator-blog-playground" && cd generator-blog-playground; fi

